// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcvnljrhutvcorkxjelp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjdm5sanJodXR2Y29ya3hqZWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwMjI2OTUsImV4cCI6MjA1MDU5ODY5NX0.oODh__EiQkptzWHjcgLz9msffT-XPHN4wbRQetLmXTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);